# Generated by Django 5.1.3 on 2024-11-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(blank=True, max_length=25, null=True)),
                ('book_price', models.IntegerField(blank=True, null=True)),
                ('book_auther_name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
