# Generated by Django 5.1.3 on 2024-11-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=25, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=25, null=True)),
                ('bank_location', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
